ProjektAplikacjiWeb/Controllers/StoreController.cs
using ProjektAplikacjiWeb.Models;
using System.Linq;
using System.Web.Mvc;

namespace ProjektAplikacjiWeb.Controllers
{
    public class StoreController : Controller
    {
        StoreContext db = new StoreContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int bookId)
        {
            var book = db.Book.Find(bookId);

            return View(book);
        }

        public ActionResult Category(string categoryname)
        {
            var category = db.Category.Include("Books").Where(cat => cat.Name.ToUpper() == categoryname.ToUpper()).Single();
            var books = category.Books.ToList();

            return View(books);
        }

        [ChildActionOnly]
        public ActionResult CategoryMenu()
        {
            return PartialView("_CategoryMenu", db.Category.ToList());
        }
    }
}

ProjektAplikacjiWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
</head>
<body>

    <!-- zastosowanie layoutów  -->
    <header>
        <div style="overflow: hidden; margin-bottom: 30px;">
            @if (@User.IsInRole("Admin"))
            {
                <a class="manageLink" href="@Url.Action("AddProduct", "Manage")">Dodaj nowy produkt</a>
            }
            <!-- widoki częściowe -->
            @Html.Partial("_LoginPartial")
        </div>
        <a id="main-header-logo" href="@Url.Content("~/")">
            <img src="@Url.Content("~/Content/Images/logo-main.png")" class="center" />
        </a>
    </header>

    <div>
        @RenderBody()
    </div>

    <footer>
        <nav>
            <ul>
                <li>@Html.ActionLink("Strona Główna", "Index", "Home")</li>
                <li>@Html.ActionLink("O nas", "StaticContent", "Home", new { viewname = "onas" }, null)</li>
                <li>@Html.ActionLink("Kontakt", "StaticContent", "Home", new { viewname = "kontakt" }, null)</li>
                <li>@Html.ActionLink("Regulamin", "StaticContent", "Home", new { viewname = "regulamin" }, null)</li>
            </ul>
        </nav>
        <div id="footer-cd-logo">
            <img src="" />
        </div>

        <div id="footer-copyright">
            Copyright &copy; 2017
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("ScriptsBottom", required: false)
</body>
</html>

ProjektAplikacjiWeb/Views/Shared/_RightSectionLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="productlist-content">

    @Html.Action("CategoryMenu", "Store")

    <div id="productlist-rightsection">
        <section class="content-section">
            <div class="section-header" style="margin-bottom: 0px;">
                <h1>
                    @RenderSection("SectionTitle", required: false)
                </h1>
            </div>

            @RenderBody()

        </section>
    </div>
</div>

@section ScriptsBottom
{
    @RenderSection("ScriptsBottom", required: false)
}